// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Post   *Post  `json:"post"`
	Author *User  `json:"author"`
}

type Post struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Comments    []*Comment `json:"comments"`
	Author      *User      `json:"author"`
}

type Query struct {
}

type User struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Posts    []*Post `json:"posts"`
}
